Typedoc deploy

diff --git a/.github/workflows/tsdoc.yml b/.github/workflows/tsdoc.yml
--- a/.github/workflows/tsdoc.yml
+++ b/.github/workflows/tsdoc.yml
@@ -1,8 +1,14 @@
-# Simple workflow for deploying static content to GitHub Pages
-name: TSDoc Actions
+# Sample workflow for building and deploying a TypeDoc site to GitHub Pages
+#
+# To get started with TypeDoc see: https://typedoc.org/guides/overview/
+#
+name: Deploy TypeDoc site to Pages
 
 on:
-  release:
+  # Runs on pushes targeting the default branch
+  push:
+    branches: [$default-branch]
+
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
@@ -12,42 +18,60 @@ permissions:
   pages: write
   id-token: write
 
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
+
 jobs:
-  # Single deploy job since we're just deploying
-  deploy:
-    name: Deploy Documentation
-
-    # Deploy to the github-pages environment
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
-
-    # Specify runner + deployment step
+  # Build job
+  build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-
-      - name: Use Bun
-        uses: oven-sh/setup-bun@v1
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
         with:
-          bun-version: latest
-
-      - name: Install deps
-        run: bun install
-
-      - name: TSDoc Action
-        run: bunx typedoc ./src/index.ts --out ./docs
-
+          node-version: "20"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
       - name: Setup Pages
-        uses: actions/configure-pages@v3
-
+        uses: actions/configure-pages@v4
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with TypeDoc
+        run: ${{ steps.detect-package-manager.outputs.runner }} typedoc --out typedoc-site
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v2
         with:
-          # Upload entire repository
-          path: './docs'
+          path: ./typedoc-site
 
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v2
+        uses: actions/deploy-pages@v3
